name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: zhinvlu68hao/commandinjection:${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Run Prisma Cloud IaC&SCA Scan
    #   id: prisma-cloud
    #   uses: bridgecrewio/checkov-action@master
    #   env:
    #     PRISMA_API_URL: https://api.sg.prismacloud.io
    #   with:
    #     api-key: ${{ secrets.BC_API_KEY }}
    #     use_enforcement_rules: true
    - name: Install and run Spectral CI
      uses: checkpointsw/spectral-github-action@v3
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN }}
        spectral-args: scan --ok --engines secrets,iac,oss --include-tags base,audit,iac
  
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ env.IMAGE_NAME }}

    # - name: Prisma Cloud image scan
    #   id: scan
    #   uses: PaloAltoNetworks/prisma-cloud-scan@v1.6.7
    #   with:
    #     pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
    #     pcc_user: ${{ secrets.PCC_USER }}
    #     pcc_pass: ${{ secrets.PCC_PASS }}
    #     image_name: ${{ env.IMAGE_NAME }}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push To Dockerhub
      id: push-to-Dockerhub
      run: docker push ${{ env.IMAGE_NAME }}

    - name: Log in with Azure
      uses: azure/login@v2.2.0
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: '${{ secrets.resource_group }}' 
        cluster-name: '${{ secrets.cluster_name }}'

    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to AKS
      id: deploy-aks
      uses: Azure/k8s-deploy@v4
      with:
        namespace: 'default'
        manifests: |
            deploy.yaml
        images: zhinvlu68hao/commandinjection:${{ github.sha }}
        pull-images: false         
